### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by ysnghr** [nadjafov05/Yoxlama#1]
Layihədəki routelar sadəcə html qaytarır. 

Bütün dataları dinamik olaraq dəyişməlidir.

**Comment by nadjafov05** [comment]
salam yasin necesen? men baxa baxa yigdigima gore tam olaraq basa dusmedim
neyi deyirsen )
qisa olaraq izah ede bilersen?

пн, 2 нояб. 2020 г. в 14:45, Yasin Uğur <notifications@github.com>:
